# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/plugins"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/shared"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/users"
    schedule:
      interval: "weekly"
