version: '3.8'
services:
  axonserver:
    image: axoniq/axonserver:2023.2.0-jdk-17-dev
    hostname: axonserver
    environment:
      - AXONIQ_AXONSERVER_DEVMODE_ENABLED=true
      - AXONIQ_AXONSERVER_STANDALONE=true
    volumes:
      - axonserver-data:/data
      - axonserver-events:/eventdata
      - axonserver-config:/config:ro
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'

  discovery-service:
    image: ghcr.io/ersms-24l/ersms-24l/discovery:latest
    ports:
      - '8761:8761'

  gateway-service:
    image: ghcr.io/ersms-24l/ersms-24l/gateway:latest
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  accounts-service:
    image: ghcr.io/ersms-24l/ersms-24l/accounts:latest
    ports:
      - '8081:8081'
    depends_on:
      - axonserver
      - mongo-db
    environment:
      - AXON_AXONSERVER_SERVERS=axonserver
      - SPRING_DATA_MONGODB_HOST=mongo-db
      - SPRING_PROFILES_ACTIVE=docker

  posts-service:
    image: ghcr.io/ersms-24l/ersms-24l/posts:latest
    ports:
      - '8082:8082'
    depends_on:
      - axonserver
      - mongo-db
    environment:
      - AXON_AXONSERVER_SERVERS=axonserver
      - SPRING_DATA_MONGODB_HOST=mongo-db
      - SPRING_PROFILES_ACTIVE=docker

  threads-service:
    image: ghcr.io/ersms-24l/ersms-24l/threads:latest
    ports:
      - '8083:8083'
    depends_on:
      - axonserver
      - mongo-db
    environment:
      - AXON_AXONSERVER_SERVERS=axonserver
      - SPRING_DATA_MONGODB_HOST=mongo-db
      - SPRING_PROFILES_ACTIVE=docker

  mongo-db:
    image: 'mongo:7.0'
    volumes:
      - mongo-db-data:/data/db
    environment:
      - 'MONGO_INITDB_DATABASE=database'
      - 'MONGO_INITDB_ROOT_PASSWORD=root'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'

volumes:
  axonserver-data:
  axonserver-events:
  axonserver-config:
  mongo-db-data:
