spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      x-forwarded:
        enabled: true
        for-enabled: true
        proto-enabled: true
        host-append: false
        port-append: false
        proto-append: false
      routes:
        - id: accounts-service
          uri: http://accounts-service.ersms-forum.svc.cluster.local:8081
          predicates:
            - Path=/accounts/**
        - id: posts-service
          uri: http://posts-service.ersms-forum.svc.cluster.local:8082
          predicates:
            - Path=/posts/**
        - id: threads-service
          uri: http://threads-service.ersms-forum.svc.cluster.local:8083
          predicates:
            - Path=/threads/**

  ssl:
    bundle:
      jks:
        pem:
          client:
            truststore:
              certificate: classpath:client.crt

server:
  ssl:
    enabled: true
    key-alias: server
    key-store: classpath:server.p12
    key-store-type: PKCS12
    key-password: secret
    key-store-password: secret
