spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      x-forwarded:
        enabled: true
        for-enabled: true
        proto-enabled: true
        host-append: false
        port-append: false
        proto-append: false
      routes:
        - id: accounts-service
          uri: https://accounts-service.ersms-forum.svc.cluster.local:8081
          predicates:
            - Path=/accounts/**
        - id: posts-service
          uri: https://posts-service.ersms-forum.svc.cluster.local:8082
          predicates:
            - Path=/posts/**
        - id: threads-service
          uri: https://threads-service.ersms-forum.svc.cluster.local:8083
          predicates:
            - Path=/threads/**
        - id: kibana
          uri: https://eck-stack-eck-kibana-kb-http.default.svc.cluster.local:5601
          predicates:
            - Path=/kibana/**
        - id: prometheus
          uri: http://prometheus-stack-kube-prom-prometheus.default.svc.cluster.local:9090
          predicates:
            - Path=/prometheus/**
        - id: grafana
          uri: http://prometheus-stack-grafana.default.svc.cluster.local:80
          predicates:
            - Path=/grafana/**
          filters:
            - RemoveRequestHeader=Host
            - RemoveRequestHeader=Origin
            - AddRequestHeader=Host, prometheus-stack-grafana.default.svc.cluster.local
            - AddRequestHeader=Origin, http://prometheus-stack-grafana.default.svc.cluster.local:80
        - id: keycloak
          uri: https://keycloak.ersms-forum.svc.cluster.local:8888
          predicates:
            - Path=/keycloak/**
        - id: frontend
          uri: http://frontend.ersms-forum.svc.cluster.local:8084
          predicates:
            - Path=/**
            - NotPath=/swagger,/swagger/**,/webjars/**,/actuator/**
      httpclient:
        ssl:
#          trusted-x509-certificates:
#            - /custom_server_certs/server.crt.pem
          use-insecure-trust-manager: true

# TODO: add support for generated ssl certificate

server:
  ssl:
    enabled: true
    trust-certificate: /custom_server_certs/server.crt.pem
    certificate: classpath:fullchain.pem
    certificate-private-key: classpath:privkey.pem
    trust-store: /server-p12/server.p12
    trust-store-password: secret
    trust-store-type: PKCS12
