spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      x-forwarded:
        enabled: true
        for-enabled: true
        proto-enabled: true
        host-append: false
        port-append: false
        proto-append: false
      routes:
        - id: accounts-service
          uri: https://accounts-service.ersms-forum.svc.cluster.local:8081
          predicates:
            - Path=/accounts/**
        - id: posts-service
          uri: https://posts-service.ersms-forum.svc.cluster.local:8082
          predicates:
            - Path=/posts/**
        - id: threads-service
          uri: https://threads-service.ersms-forum.svc.cluster.local:8083
          predicates:
            - Path=/threads/**
        - id: frontend
          uri: https://frontend.ersms-forum.svc.cluster.local:8084
          predicates:
            - Path=/**
            - NotPath=/swagger,/swagger/**,/webjars/**,/actuator/**

server:
  ssl:
    enabled: true
    key-alias: server
    key-store: classpath:server.p12
    key-store-type: PKCS12
    key-password: secret
    key-store-password: secret
    trust-store: classpath:client.jks
    trust-store-password: secret
