eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

spring:
  cloud:
    gateway:
      x-forwarded:
        enabled: true
        for-enabled: true
        proto-enabled: true
        host-append: false
        port-append: false
        proto-append: false
      routes:
        - id: accounts-service
          uri: lb://ACCOUNTS
          predicates:
            - Path=/accounts/**
          filters:
            - StripPrefix=1
        - id: posts-service
          uri: lb://POSTS
          predicates:
            - Path=/posts/**
          filters:
            - StripPrefix=1
        - id: threads-service
          uri: lb://THREADS
          predicates:
            - Path=/threads/**
          filters:
            - StripPrefix=1
        - id: frontend-dev
          uri: http://${DOCKER_GATEWAY_HOST:host.docker.internal}:8085
          predicates:
            - Path=/frontend-dev/**
          filters:
            - StripPrefix=1
        - id: frontend
          uri: http://frontend:8084
          predicates:
            - Path=/**
            - NotPath=/swagger,/swagger/**,/webjars/**,/actuator/**
