---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keycloak
  name: keycloak
  namespace: ersms-forum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  strategy: {}
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      volumes:
        - name: cert-volume
          secret:
            secretName: cert-pem-1
            items:
              - key: client.pem
                path: client.pem
        - name: server-cert-volume
          secret:
            secretName: server-cert
            items:
              - key: server.crt.pem
                path: server.crt.pem
        - name: server-key-volume
          secret:
            secretName: server-key
            items:
              - key: server.key.pem
                path: server.key.pem
      containers:
        - image: quay.io/phasetwo/phasetwo-keycloak:24.0.3
          name: keycloak
          # TODO: use production ready `start`
          args: [
            "start-dev",
            "--truststore-paths=/custom_certs/client.pem",
            "--https-certificate-file=/custom_server_certs/server.crt.pem",
            "--https-certificate-file=/custom_server_keys/server.key.pem",
            "--http-enabled=false"
          ]
          volumeMounts:
            - name: cert-volume
              mountPath: "/custom_certs"
              readOnly: true
            - name: server-cert-volume
              mountPath: "/custom_server_certs"
              readOnly: true
            - name: server-key-volume
              mountPath: "/custom_server_keys"
              readOnly: true
          livenessProbe:
            httpGet:
              path: /keycloak/realms/master/
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 120
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /keycloak/realms/master/
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 60
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          resources:
            requests:
              cpu: 125m
              memory: 250Mi
          env:
            - name: KC_HTTP_RELATIVE_PATH
              value: "/keycloak/"
            - name: KC_HOSTNAME_ADMIN_URL
              value: "https://ersms3.kwojda.pl/keycloak/"
            - name: KC_HOSTNAME_URL
              value: "https://ersms3.kwojda.pl/keycloak/"
            - name: KC_PROXY
              value: "edge"
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kc-admin-pass
                  key: KC_ADMINPASSWORD
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              value: "jdbc:postgresql://postgres:5432/keycloak"
            - name: KC_DB_USERNAME
              value: "keycloak"
            - name: KC_DB_PASSWORD
              value: "keycloak"
          ports:
            - containerPort: 8443
      restartPolicy: Always
status: {}
