
spring:
  webflux:
    base-path: /accounts

  ssl:
    bundle:
      jks:
        pem:
          client:
            truststore:
              certificate: classpath:client.crt

server:
  ssl:
    enabled: true
    key-alias: server
    key-store: classpath:server.p12
    key-store-type: PKCS12
    key-password: secret
    key-store-password: secret
