---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ersms-forum-config
  namespace: ersms-forum
data:
  application.yaml: |-
    server:
      shutdown: graceful
      lifecycle:
        timeout-per-shutdown-phase: 15
      port: 8080
      compression:
        enabled: true
        mime-types: application/json,text/css,application/javascript
        min-response-size: 2048

    # Logging
    logging.level.org.springframework: INFO

    # Metrics
    management:
      endpoint:
        health:
          probes:
            enabled: true
      health:
        livenessState:
          enabled: true
        readinessState:
          enabled: true
        restart:
          enabled: true
        metrics:
          enabled: true
        # TODO: consider using prometheus
        prometheus:
          enabled: true
      endpoints:
        web:
          exposure:
            include: '*'
      metrics:
        export:
          prometheus:
            enabled: true

      # TODO: consider using sleuth: spring-cloud-starter-sleuth for log tracing
      sleuth:
        sampler:
          probability: 1.0
        config:
          # Allow the microservices to override the remote properties with their own System properties or config file
          allow-override: true
          # Override configuration with any local property source
          override-none: true
      cloud:
        kubernetes:
          discovery:
            enabled: true
        loadbalancer:
          ribbon:
            enabled: false
        gateway:
          x-forwarded:
            enabled: true
            for-enabled: true
            proto-enabled: true
            host-append: false
            port-append: false
            proto-append: false
      
