---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: axonserver
  name: axonserver
  namespace: ersms-forum
spec:
  ports:
    - name: "http"
      port: 8024
      targetPort: 8024
    - name: "grpc"
      port: 8124
      targetPort: 8124
    - name: "internal"
      port: 8224
      targetPort: 8224
  selector:
    app: axonserver
