---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway-service
  name: gateway-service
  namespace: ersms-forum
spec:
  ports:
    - name: "http"
      port: 443
      targetPort: 8080
  selector:
    app: gateway-service
  type: LoadBalancer
status:
  loadBalancer: { }
