---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: accounts-service
  name: accounts-service
  namespace: ersms-forum
spec:
  ports:
    - name: "http"
      port: 8081
      targetPort: 8081
  selector:
    app: accounts-service
status:
  loadBalancer: { }
