---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: posts-service
  name: posts-service
  namespace: ersms-forum
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    app: posts-service
status:
  loadBalancer: { }
