---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: threads-service
  name: threads-service
  namespace: ersms-forum
spec:
  ports:
    - name: "http"
      port: 8083
      targetPort: 8083
  selector:
    app: threads-service
status:
  loadBalancer: { }
