---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
  name: keycloak
  namespace: ersms-forum
spec:
  ports:
    - name: "http"
      port: 8888
      targetPort: 8443
  selector:
    app: keycloak
status:
  loadBalancer: { }
