---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: ersms-forum
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 80
    - name: "https"
      port: 443
      targetPort: 443
      protocol: TCP
    - name: "quic"
      port: 443
      targetPort: 443
      protocol: UDP
  type: LoadBalancer
  selector:
    app: frontend
