---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: ersms-forum
spec:
  ports:
    - name: "http"
      port: 8084
      targetPort: 8084
  selector:
    app: frontend
