eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

spring:
  webflux:
    base-path: /

server:
  forward-headers-strategy: framework
