
spring:
  webflux:
    base-path: /threads

server:
  ssl:
    enabled: true
    key-alias: server
    key-store: /server-p12/server.p12
    key-store-type: PKCS12
    key-password: secret
    key-store-password: secret
    trust-certificate: /custom_server_certs/server.crt.pem

axon:
  axonserver:
    servers: axonserver.ersms-forum.svc.cluster.local
    ssl-enabled: true
    cert-file: /custom_server_certs/server.crt.pem
