
spring:
  webflux:
    base-path: /threads

server:
  ssl:
    enabled: true
    key-alias: server
    key-store: classpath:server.p12
    key-store-type: PKCS12
    key-password: secret
    key-store-password: secret
    trust-certificate: classpath:client.pem
