name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: read

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: temurin

      - name: Update Gradle Wrapper
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          paths: |
            plugins/**
            shared/**
            accounts/**
            posts/**
            threads/**
            discovery/**
            gateway/**
